container:
  image: crystallang/crystal:latest

spec_task:
  shard_cache:
    fingerprint_script: cat shard.lock
    populate_script: shards install
    folder: ~/.cache/shards
  install_script: shards install # always install to populate work dir cache
  spec_script: crystal spec